import { task } from "hardhat/config";
import type { TaskArguments } from "hardhat/types";
import path from "node:path";
import { promises as fs } from "node:fs";

type DeploymentJson = {
  address: string;
  abi: unknown[];
};

async function readDeployment(filePath: string): Promise<DeploymentJson> {
  const raw = await fs.readFile(filePath, "utf8");
  const parsed = JSON.parse(raw) as DeploymentJson;
  if (!parsed.address || !Array.isArray(parsed.abi)) {
    throw new Error(`Invalid deployment file: ${filePath}`);
  }
  return parsed;
}

task("task:sync-frontend", "Sync deployed addresses and ABIs into the Vite frontend")
  .addOptionalParam("deploymentNetwork", "Deployments folder to read from (default: sepolia)")
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const deploymentNetwork = (taskArguments.deploymentNetwork as string | undefined) || "sepolia";
    const root = hre.config.paths.root;

    const deploymentsDir = path.join(root, "deployments", deploymentNetwork);
    const czamaPath = path.join(deploymentsDir, "ConfidentialZama.json");
    const swapPath = path.join(deploymentsDir, "CZamaSwap.json");

    const czama = await readDeployment(czamaPath);
    const swap = await readDeployment(swapPath);

    const outPath = path.join(root, "app", "src", "config", "contracts.ts");

    const file = `// Auto-generated by "npx hardhat task:sync-frontend --deploymentNetwork ${deploymentNetwork}".
// Source: deployments/${deploymentNetwork}/ConfidentialZama.json and deployments/${deploymentNetwork}/CZamaSwap.json
// Do not edit manually.

export const CZAMA_TOKEN_ADDRESS = '${czama.address}' as const;
export const CZAMA_SWAP_ADDRESS = '${swap.address}' as const;

export const CZAMA_TOKEN_ABI = ${JSON.stringify(czama.abi, null, 2)} as const;

export const CZAMA_SWAP_ABI = ${JSON.stringify(swap.abi, null, 2)} as const;
`;

    await fs.writeFile(outPath, file, "utf8");
    console.log(`Synced frontend contract config: ${path.relative(root, outPath)}`);
  });

